(bind-key* (kbd "C-+") 'my/zoom-in)
(bind-key* (kbd "C--") 'my/zoom-out)
(bind-key* (kbd "C-0") 'my/zoom-default)


;; Global
(global-unset-key (kbd "M-1"))
(global-unset-key (kbd "M-2"))
(global-unset-key (kbd "M-3"))
(global-unset-key (kbd "M-4"))
(global-unset-key (kbd "M-5"))
(global-unset-key (kbd "M-6"))
(global-unset-key (kbd "M-7"))
(global-unset-key (kbd "M-8"))
(global-unset-key (kbd "M-9"))

;; (define-key global-map (kbd "M-S") (lambda () (interactive) (my/tab-set-buffer "semi-home")))
(use-package bind-key
  :ensure t)

(bind-key* (kbd "M-1") (lambda () (interactive) (my/tab-jump-to 1)))
(bind-key* (kbd "M-2") (lambda () (interactive) (my/tab-jump-to 2)))
(bind-key* (kbd "M-3") (lambda () (interactive) (my/tab-jump-to 3)))
(bind-key* (kbd "M-4") (lambda () (interactive) (my/tab-jump-to 4)))
(bind-key* (kbd "M-5") (lambda () (interactive) (my/tab-jump-to 5)))
(bind-key* (kbd "M-6") (lambda () (interactive) (my/tab-jump-to 6)))
(bind-key* (kbd "M-7") (lambda () (interactive) (my/tab-jump-to 7)))
(bind-key* (kbd "M-8") (lambda () (interactive) (my/tab-jump-to 8)))
(bind-key* (kbd "M-9") (lambda () (interactive) (my/tab-jump-to 9)))
(bind-key* (kbd "M-h") (lambda () (interactive) (my/tab-jump-to-buffer "home")))
(bind-key* (kbd "M-H") (lambda () (interactive) (my/tab-set-buffer "home")))
(bind-key* (kbd "M-s") (lambda () (interactive) (my/tab-jump-to-buffer "semi-home")))
(bind-key* (kbd "M-S") (lambda () (interactive) (my/tab-set-buffer "semi-home")))

(define-key global-map (kbd "M-1") (lambda () (interactive) (my/tab-jump-to 1)))
(define-key global-map (kbd "M-2") (lambda () (interactive) (my/tab-jump-to 2)))
(define-key global-map (kbd "M-3") (lambda () (interactive) (my/tab-jump-to 3)))
(define-key global-map (kbd "M-4") (lambda () (interactive) (my/tab-jump-to 4)))
(define-key global-map (kbd "M-5") (lambda () (interactive) (my/tab-jump-to 5)))
(define-key global-map (kbd "M-6") (lambda () (interactive) (my/tab-jump-to 6)))
(define-key global-map (kbd "M-7") (lambda () (interactive) (my/tab-jump-to 7)))
(define-key global-map (kbd "M-8") (lambda () (interactive) (my/tab-jump-to 8)))
(define-key global-map (kbd "M-9") (lambda () (interactive) (my/tab-jump-to 9)))
(define-key global-map (kbd "M-h") (lambda () (interactive) (my/tab-jump-to-buffer "home")))
(define-key global-map (kbd "M-H") (lambda () (interactive) (my/tab-set-buffer "home")))
(define-key global-map (kbd "M-s") (lambda () (interactive) (my/tab-jump-to-buffer "semi-home")))
(define-key global-map (kbd "M-S") (lambda () (interactive) (my/tab-set-buffer "semi-home")))

(message "999-bindings.el was loaded.")
